remote_theme: pages-themes/cayman@v0.2.0

plugins:
- jekyll-remote-theme 

title: [Evelyn YuJou]
description: [Mon site personnel]
css: /assets/css/styles.css
  display: inline-block; /* Horizontal arrangement of menu items */
  margin-right: 20px; /* Menu item spacing */
}

a {
  color: #ccc; /* Light gray menu link color */
  text-decoration: none; /* Remove link underline */
  padding: 5px 10px; /* Menu item inner padding */
}

a:hover {
  color: #fff; /* White link color on hover */
  background-color: #666; /* Medium gray background on hover */
}

/* Home, Profile, and CNRS Sections */
section {
  padding: 20px; /* Add padding around each section for spacing */
  margin-bottom: 30px; /* Add margin between sections for spacing */
  background-color: #fff; /* White background for sections */
  border: 1px solid #ccc; /* Add a light gray border to sections */
  border-radius: 5px; /* Add rounded corners to sections */
}

h2 {
  color: #333; /* Dark gray heading color */
}

img {
  max-width: 100%; /* Ensure the profile image fits within its container */
}

p {
  line-height: 1.6; /* Set a comfortable line-height for paragraphs */
}

